# Generated by Django 2.1.5 on 2019-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
